Fix copy in firefox and warn about pasting
openflighthpc/flight-desktop-webapp pull request #55
Opened 2021-05-26 10:40 UTC by WilliamMcCumstie

`firefox` does not implement the `clipboard` API like the rest of the modern browsers. This means the `copy` and `paste` features do not work.

Fix the `copy` feature is "reasonable" straight forward by adding the following fallback:
* Create a temporary `textarea` and dump the payload into it,
* Copy from the `textarea` using `execCommand("copy"), and 
* Remove the `textarea`.

There are a couple of idiosyncrasies involved, particularly the `textarea` needs to be in a `block` style. As the `textarea` only exists briefly, it does not appear to be rendered by the browser. As it appears to be working, this implementation should be sufficient to move forward to acceptance testing.

---

Pasting is a different story... tl;dr It doesn't work

Browsers put various permission safe guards around reading from the clipboard as it commonly contains sensitive information (e.g. passwords). In `chrome` this takes the form of a dialog box prompting the user to provide the required permissions. `firefox` does not do this....

Instead `firefox` only allows access to the `clipboard` API in browser extensions. I attempted to use the `execCommand("paste")` action, however this gets disabled as well. AFAICS, it is not possible to programmatically  paste within `firefox`.

Instead a `toast` error is emitted telling the user that paste has been disabled and they will need to use a different browser.

2021-06-01 14:42 UTC, benarmston requested changes
The copy functionality works.  I've added comments to it so that it can be brought in line with modern JavaScript and React usage.

We can get paste functionality to work for Firefox too.  We need to change the behaviour of the "Prepare paste" button so that it does the following:

1. Attempt "sane browser" paste
2. Catch the error that results.
3. Display a modal dialog containing a textarea; a prompt for the user to paste their text into the textarea and a "Complete paste preparation" button.
4. The "complete paste preparation" button has an onclick handler that reads the content of the textarea and calls `vnc.current.setClipboardText(...)`.

2021-06-01 14:42 UTC, benarmston commented on src/NoVNC.js
> +        var input = document.createElement("textarea");
Modern javascript uses either `const` or `let`, but not `var`.  `const` when the variable won't be reassigned; `let` when it will.

2021-06-01 14:42 UTC, benarmston commented on src/NoVNC.js
> +          input.style.display = "block";
We should also set `visibility: hidden`, `height: "1px"` and `maxHeight: "1px"`.

2021-06-01 14:42 UTC, benarmston commented on src/NoVNC.js
> +        var input = document.createElement("textarea");
It's bad practice for a React component to be mutating the DOM like this.  I see that this method is actually used as an event handler by `RFB`, but the `VncContainer` is bringing that into the React world.

This should be changed so that the render method of `VncContainer` creates the fallback DOM elements it needs and creates a  React reference to them.

```
  render() {
    return (
      <React.Fragment>
        <div
          ref={this.noVNCCanvas}
          className={`${styles.NoVNCWrapper} fullscreen-content`}
        />
        <textarea ref={this.copyFallback} style={{display: "none", ...}}></textarea>
      </React.Fragment>
    )
  }

```

The `onClipboard` method is then updated to use `this.copyFallback`.  Something like

```
        this.copyFallback.style.display = "block";
        this.copyFallback.select();
        if (document.execCommand('copy')) {
          // ...
        }
        this.copyFallback.style.display = "none";
```

I've not tested any of that code.  But something along those lines will work.

2021-06-04 17:16 UTC, WilliamMcCumstie commented on src/NoVNC.js
> +        var input = document.createElement("textarea");
c6a91f0eb116275eadef2b2bfdeb708b6e6b6ff8

2021-06-04 17:49 UTC, WilliamMcCumstie commented on src/NoVNC.js
> +        var input = document.createElement("textarea");
9363142349ec0b181055272c2ba080fadb7ab0ef

2021-06-04 17:53 UTC, WilliamMcCumstie commented on src/NoVNC.js
> +          input.style.display = "block";
The `visibility: hidden` style doesn't work, so I have omitted it. Otherwise I have added the height tags

1f60db62618711767622bfe11f43ab8b38fb71a6

2021-06-10 13:04 UTC, benarmston approved these changes
I've added commits to fix the issues I identified below.

I've also done some refactoring to extract a reasonably generic "paste preparation" component.  This might be useful in the future, it certainly makes `Toolbar` easier to understand now.

The fallback modal copy has been updated.  It now instructs the user on what to do and what will happen.

2021-06-10 13:04 UTC, benarmston commented on src/SessionPage.js
> +      fallbackText.current.value = "";
This isn't needed.  React mounts and unmounts the modal which removes it and the textarea from the DOM.

2021-06-10 13:04 UTC, benarmston commented on src/SessionPage.js
> +            toggleFallback();
As discussed, we want the fallback to work for all browsers if needed.

2021-06-10 13:04 UTC, benarmston commented on src/SessionPage.js
> +          } else { // The paste will fail unless using HTTPs
You were right about this.  `navigator.clipboard` returns `null` when accessed over HTTP.  In that case all browsers now fallback to the fallback.

2021-06-10 13:07 UTC, benarmston commented
I also added a toast when the paste has been prepared.

The "Prepare paste" button is now only displayed when the VCN session is connected.  It doesn't work when not connected.

2021-06-10 13:07 UTC, benarmston commented
Thanks for all your work on this @WilliamMcCumstie .  This LGTM.

2021-06-10 13:08 UTC, merged

2021-06-11 14:46 UTC, WilliamMcCumstie commented on src/SessionPage.js
> +            this.vnc.current.setClipboardText(text);
:cry:

2021-06-11 14:46 UTC, WilliamMcCumstie commented on src/SessionPage.js
> +      fallbackText.current.value = "";
:+1:

2021-06-11 14:46 UTC, WilliamMcCumstie commented on src/SessionPage.js
> +            toggleFallback();
:+1:

2021-06-11 14:46 UTC, WilliamMcCumstie commented on src/SessionPage.js
> +          } else { // The paste will fail unless using HTTPs
:mage: