Allow users to update their configs and quick launch sessions
openflighthpc/flight-desktop-webapp pull request #62
Opened 2021-07-12 13:25 UTC by WilliamMcCumstie

There is a new page under `/configs` which allows the user to update their configuration. This will poll for the current list of verified `desktop` types and display them in a list. There is some special handling when the default desktop has not been verified.

In addition, a `Quick launch session` button/link has been added to the nav bar. Currently it will re-create a session each time the user connects. Possible this should be extended to re-connect to an existing session.

2021-08-05 17:40 UTC, benarmston requested changes
Thanks for your work on this @WilliamMcCumstie .  Having a quick launch button is very nice.

I've added a few comments below for you to look at mostly related to styling and user-visible copy.

2021-08-05 17:40 UTC, benarmston commented on src/ConfigsPage.js
> +                <DesktopOptions desktops={desktops}/>
This drop down doesn't seem quite right.  It's not clear that the disabled option is the default.  If I change the desktop type but then want to change back it isn't entirely clear how I select that default again.

There are a couple of options to address this:

1. Remove the disabled option and use the `selected` attribute on `option`.  Add a simple indicator to the default desktop, perhaps `*` or `(default)`.
2. Switch over to [React Select](https://react-select.com/home). Remove the disabled option; use the `defaultValue` prop; add nice styling to the default option.

Can you take a look at one of the above options please?  Option (1) is perfectly fine if (2) is awkward FSR.

2021-08-05 17:40 UTC, benarmston commented on src/ConfigsPage.js
> +            </Col>
We spoke about this briefly before.  The geometry for the desktop controls both the VNC session size and the X session size via `xrandr`.  The latter is done by [installing](https://github.com/openflighthpc/flight-desktop-types/blob/master/gnome/session.sh#L116) the [geometry script](https://github.com/openflighthpc/flight-desktop-types/blob/master/gnome/flight-desktop_geometry.sh).  Other desktops have something similar.

As these are intended for xrandr input, we should ensure that they are sensible values for xrandr.  As a first pass, hard coding  the following values would sufficient.  Later we're likely to want to determine which of these values are supported by the machine running, and to also given them better names, e.g., Tablet, Large Laptop, Mobile etc..


 * 1920x1200
 * 1920x1080
 * 1600x1200
 * 1680x1050
 * 1400x1050
 * 1360x768 
 * 1280x1024
 * 1280x960 
 * 1280x800 
 * 1280x720 
 * 1024x768 
 * 800x600  
 * 640x480  


Obviously, this change implies that a single select would be used rather than two inputs.

2021-08-05 17:40 UTC, benarmston commented on src/api.js
> +  return { request, patch: patch };
FYI: `{ variableName }` is equivalent to `{ variableName: variableName }`. So the above could be shortened to `{ request, patch }`.

2021-08-09 15:13 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +      Your configurations have been updated!
23a39a9a34a36b40279c64b864ac049188316388

2021-08-09 15:15 UTC, WilliamMcCumstie commented on src/api.js
> +  return { request, patch: patch };
ee2ce3f39ef2bee10cf438d003d1b97268b9eb6f

2021-08-09 15:15 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +  const d = desktops.map(d => { return d.id }).includes(configs.desktop) ? configs.desktop : null;
ee2ce3f39ef2bee10cf438d003d1b97268b9eb6f

2021-08-09 15:30 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +                <DesktopOptions desktops={desktops}/>
bddfb5814c6fe51681c01bba0002eaf310b153da

2021-08-09 15:38 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +      element = <option key={desktop.id}>{desktop.id}</option>
f0104521d7eac6e188f363b6c74e33bbafe72380

2021-08-09 16:14 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +  return <Button color="success" className="pull-right" disabled={!modified} onClick={submit}>
cec78525aa443877e93726d6aa7a208f14ac14d4

2021-08-09 17:30 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +          </FormGroup>
778c333eceb159bfb8657be94a54430609219f43

2021-08-09 17:30 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +          </FormGroup>
778c333eceb159bfb8657be94a54430609219f43

2021-08-09 17:41 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +            </Col>
c4e583830254f321b3aa553f9a52a79a079a1f3d

2021-08-16 10:28 UTC, benarmston requested changes
This is looking much better @WilliamMcCumstie .  I have a few more changes for you to look at please.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +      element = <option value={desktop.id} label={label} selected={is_selected}/>
Same for `GeometryOptions`.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +    if (desktop.verified) {
We should include all desktop types not just verified ones.  Its possible that a desktop type might be verified on the compute nodes but not on the head node.  We want to allow the user to set the default suitable for the compute nodes.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +      return <Layout configs={config_req.data} desktops={desktop_req.data.data} />
The desktops should be extracted from the request via `flight-webapp-components` `utils.getResourcesFromResponse(data)` function.  It has some useful error handling in it.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +    const is_selected = (selected === desktop.id);
We don't need `is_selected` here.  The `value` property on the `select` is sufficient and the correct way of doing this.  I think I may have suggested using `selected` in a previous comment.

Also JS variables should be `camelCase` not `under_score`.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +    return <option value={geometry} label={label} selected={is_selected}/>
Again, we don't need `selected`.  We do need `key`.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +  const { request, patch } = useUpdateUserConfig();
FYI: this could be `const { request, response, patch } = ...` which would change a later line from `if (request.response.ok)` to `if (response.ok)`.  I think the latter reads a little nicer.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +  const is_original = (desktop === originalStruct.desktop) && (geometry === originalStruct.geometry);
Can we have `isOriginal` instead of `is_original`.

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +    <span>{request.loading ? "Updating Configuration..." : "Update Configuration"}</span>
This should be `Updating...` rather than `Updating Configuration...`.  That has better consistency with our other "action buttons".

2021-08-16 10:28 UTC, benarmston commented on src/ConfigsPage.js
> +    header: 'Failed to update configuration',
This should be "your configuration".  We refer to "your configuration" most everywhere else.

2021-08-16 11:21 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +      element = <option value={desktop.id} label={label} selected={is_selected}/>
c5e32db319fcee07cfce4d8bbeb4c806bfcdd8f0

2021-08-16 11:45 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    if (desktop.verified) {
This is an easy enough change, however IMO it is premature.

Currently the `quick launch` button uses this setting to fire up new desktops. Setting the default to an unverified desktop will break this feature.

This leaves one of three options:

1. Do nothing, `quick launch` will continue to operate correctly if configured via the webapp,
2. Conditionally disable `quick launch` (will likely require an additional request), or
3. Accept that `quick launch` may fail depending on the configuration.

---

## Option 3: Breaking Quick Launch and Poor UX

_Technically_ the `quick launch` button can fail if the user re-configures the `flight-desktop` via CLI. This in general, leads to a poor UX and should be avoided. It is however an "advance use case" and pre-existing issue.

However, re-configuring the `flight-desktop` via the webapp is a relatively simple use case. This should not lead to `quick launch` button breaking. This rules out option 3.

---

## Option 2: Disable Quick Launch

This option is do-able, but means each page load will need to determine if the default desktop has been verified.

This raises a few headaches as it will either require:

* An additional request to `flight-desktop-restapi` on every page load, or
* Some how cache the request and periodically update it.

Both of these options raise their own issues and ideally would be avoided.

tl;dr Option 2 is doable, but is a bit of a pain.

---

## Option 1: Do not allow unverified desktops

This is the do-nothing option, and accept the default can not be set to an unverified desktop. This has the following implications to the `quick launch` button:

* It should function correctly when configured via the `webapp`, and
* It may break when configured via the `CLI`.

Currently the `webapp` does not support launching desktops on remote machine, so the functionality should focus on the host. For this reason, the do nothing option is probably best.

At some point, we will likely need to address the question:
_What if remote nodes have different verified desktops?_

However this should be done in such a way not to break the `quick launch`. However these issues can be kicked down the road.

2021-08-16 12:04 UTC, benarmston commented on src/ConfigsPage.js
> +    if (desktop.verified) {
You raise a good point about the "quick launch" button being coupled to this setting.  For now, add `disabled` `option`s for the desktop types that are reported as being unverified.  That's a better UX than them simply being omitted.

I'll have a think about how this should work for desktop types that have different verification states on the head node and compute nodes.

2021-08-16 12:05 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    const is_selected = (selected === desktop.id);
887b565482bc47b1c82d0bdc80b54c5c0655fd3f

2021-08-16 12:05 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    return <option value={geometry} label={label} selected={is_selected}/>
Done with `DesktopOptions` commits

2021-08-16 12:09 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +  const { request, patch } = useUpdateUserConfig();
b2fd156eb9673a045392aee00d2160dcdcf72aea

2021-08-16 12:10 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    header: 'Failed to update configuration',
35d894c5154787122650e1cb707a772cb6f48ea5

2021-08-16 12:10 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    <span>{request.loading ? "Updating Configuration..." : "Update Configuration"}</span>
35d894c5154787122650e1cb707a772cb6f48ea5

2021-08-16 12:11 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +  const is_original = (desktop === originalStruct.desktop) && (geometry === originalStruct.geometry);
35d894c5154787122650e1cb707a772cb6f48ea5

2021-08-16 14:16 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +      return <Layout configs={config_req.data} desktops={desktop_req.data.data} />
The `desktop_req.data.data` exists because it is generally bad practice to return an `array` from an AP (Although I do believe the particular CSRF this pertains to has been resolved).

However the other GET requests do not have a `data` key. This has been a long standing implementation of `flight-desktop-restapi`.

---

As far as the additional error handling, the `response` is already checked to be `OK`. This should be sufficient to infer that `desktop_req.data.data` will be an array.

2021-08-16 14:37 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +  const { request, patch } = useUpdateUserConfig();
This change does not work FSR. Assumable the `loading` variable would need to be waited on

I do not the resolve to dig through `useFetch` to work out why it doesn't work. So I have reverted the change to `request.response`:

dc3157fdb743163b3cc8f4b35438f3c48ba595fc

2021-08-16 15:43 UTC, WilliamMcCumstie commented on src/ConfigsPage.js
> +    if (desktop.verified) {
2cc3a7edc0954febc37ad474fb3cb9e3643f4a43

2021-08-16 17:47 UTC, benarmston approved these changes
You misunderstood what I was after with the `selected` attribute on `option`.  Instead of

```
<select value="something">
  <option value="something" selected="true">Something</option>
  <option value="something-else">Something else</option>
</selected>
```

we should instead have

```
<select value="something">
  <option value="something">Something</option>
  <option value="something-else">Something else</option>
</selected>
```

The `value` attribute on `select` determines which `option` is selected.  The `selected` attribute on `option` is ignored and therefore confusing.

I've made that change a few other stylistic changes.

2021-08-16 17:47 UTC, benarmston commented on src/ConfigsPage.js
> +  const { request, patch } = useUpdateUserConfig();
Fair enough.

2021-08-16 17:48 UTC, benarmston commented
LGTM.

2021-08-16 17:48 UTC, merged