Launch session dropdown
openflighthpc/flight-desktop-webapp pull request #84
Opened 2022-04-14 12:10 UTC by VoxSecundus

NB: This PR is based off of #83 and includes changes made on that branch. It should be rebased once #83 has been merged into `master.`

This PR includes work done to convert a pair of buttons on the `BrandBar` used to launch new desktop sessions into a single, split dropdown button. The main button has the old `Launch new session` functionality (takes you to `/sessions/new`); the one dropdown item is `Quick launch session`, which retains the same functionality (tries to launch a one-click session of whatever Flight Desktop's default is).

2022-04-14 17:12 UTC, benarmston requested changes
Can you look at the below @VoxSecundus and whilst doing that also change "My sessions" to "Sessions".

2022-04-14 17:12 UTC, benarmston commented on src/LaunchDropdown.js
> +      className={className}
Can we add `dropdown` to the classes here.  It fixes a styling issue.  

![image](https://user-images.githubusercontent.com/287050/163439327-d438b01e-522a-4402-b284-ded3a39833ec.png)

vs

![image](https://user-images.githubusercontent.com/287050/163439364-deaa403b-d8fa-4aca-abbe-2c7cc8f8ff74.png)

2022-04-14 17:22 UTC, VoxSecundus commented on src/LaunchDropdown.js
> +      className={className}
Just adding `dropdown` doesn't change anything for me

2022-04-14 17:42 UTC, benarmston reviewed
FSR, quick launching the desktop session now gives a spurious error message about the desktop not having been configured.  "Slow launching" does not.

Investigation needed.

2022-04-19 11:00 UTC, VoxSecundus commented
> FSR, quick launching the desktop session now gives a spurious error message about the desktop not having been configured. "Slow launching" does not.

The same occurs on the `master` branches of `flight-desktop-webapp`/`flight-landing-page`/`flight-webapp-components`.

2022-04-25 14:56 UTC, merged