Naming/renaming sessions
openflighthpc/flight-desktop-webapp pull request #89
Opened 2022-06-08 14:45 UTC by VoxSecundus

This PR adds the ability for Flight Desktop Webapp to (optionally) give their desktop sessions a name, and the ability to rename existing sessions.

## Naming a new session

The previous functionality of a one-click `Launch` button has been replaced with a modal containing a quick explanation and input for the session name:

![Screenshot_2022-06-08_15-37-45](https://user-images.githubusercontent.com/12374447/172644402-0436c6e2-7766-4e54-91e0-6f148e6636e0.png)

## Renaming a session

A new button component has been created to accommodate renaming sessions. Clicking the `Rename` button raises a popover with an input for the new name (or a blank space, if you want to unset the name), with a pair of buttons to confirm or cancel. The button has been added to the session page and the session card component page. The name on-screen is updated automatically once the rename request has completed.

**Session card:**

![Screenshot_2022-06-08_15-39-24](https://user-images.githubusercontent.com/12374447/172645096-7d06e97e-ca15-44f4-8a25-2d09121b6ca6.png)

**Session page:**

![Screenshot_2022-06-08_15-39-38](https://user-images.githubusercontent.com/12374447/172645119-3c0e3500-0377-4eda-a118-4a244619d448.png)

**Rename popover:**

![Screenshot_2022-06-08_15-41-43](https://user-images.githubusercontent.com/12374447/172645300-1a8d85b6-889b-472b-b56d-107c83511645.png)

2022-06-08 15:55 UTC, benarmston requested changes
@VoxSecundus my first set of comments on this.  I've not looked through the code yet, so there may be some others once these have been addressed.

## Comments about the UI/UX of the session launch configuration modal

* Launching an Xfce desktop results in the modal title being `Prepare launch of 'Xfce desktop' desktop`.  This reads awkwardly.  The final "desktop" should be omitted if the name of the desktop ends with "desktop".
* The desktop name in the modal should use italics instead of quotes.
* The modal title should read "Configure this <desktop> session".
* The modal buttons should be small.  (This is inconsistent with the Flight Job modal, but I now think Flight Job is wrong).
* The "< Back" button should be "Cancel".
* The "Start" button should be "Launch" with the same "lightning" icon as the desktop card uses.
* The session name input label should read: "Give your session a name to more easily identify it (optional)."
* There should be some vertical space between the text "Please input a sensible name..." and the input field.
* Clicking on the "Please input a sensible name..." text should focus the input field.  I.e., it should be a `label`.

## Comments about the UI/UX of the session rename dialog

* The rename input should be pre-populated with the session's current name.
* The label should read: "Enter new name (leave blank to remove the name)."
* The input should be automatically focused when the form is displayed.
* Clicking the label should focus the name form.
* Clicking enter when the input has focus should submit the form.

2022-06-09 11:51 UTC, benarmston commented
Further to the above, whilst I like having the rename button on the session listing page, we need to deal with narrower browser widths better.  The below image is taken on a browser width of 1560px so the issue isn't *very* narrow browsers.

![image](https://user-images.githubusercontent.com/287050/172839690-7c589a97-7a5e-4a90-bcfa-efd1b405bf2f.png)

2022-06-14 15:16 UTC, benarmston requested changes
There are another couple of UX/UI issues for you to look at please and I've noticed some warnings too.

---

There are a number of warnings.  Could you take a look at fix them please.

![image](https://user-images.githubusercontent.com/287050/173611502-56992fe6-7023-42eb-8ea4-ad0c1400bc07.png)

---

There are still issues with sizing of the buttons on the list page.  For now let's remove the button from this page and we'll look at adding it back in a later release.

![image](https://user-images.githubusercontent.com/287050/173611850-115c1a45-e3f8-45c3-bc9e-f486e82237ec.png)

---

The rename popover is much easier to use now that it auto focuses the input and submits on enter.   The launch modal should do the same too please.

2022-06-14 17:12 UTC, benarmston requested changes
This should be the last set of comments I have on this PR.  Can you take a look at the below please?

2022-06-14 17:12 UTC, benarmston commented on src/SessionCard.js
> +    flexWrap: 'nowrap'
Is this styling still needed?  If it is can we use the bootstrap class `.flex-nowrap` instead.  It's better to be consistent in preferring bootstrap utility classes to using the `style` property.

2022-06-14 17:12 UTC, benarmston commented on src/SessionPage.js
> +    </RenameButton>
If a component doesn't have any children we should prefer closing it with `/>` instead of `><...>`.

2022-06-14 17:12 UTC, benarmston commented on src/launch-and-access-desktop-session.test.js
> +  const launchButton = within(card).getByTestId('launch-modal-button');
According to https://testing-library.com/docs/queries/bytestid `getByTestId` should only be used if their other methods don't work.  This is fine for now and doesn't need changing, but I wanted to make sur that you were aware of that.

2022-06-14 19:40 UTC, VoxSecundus commented on src/DesktopCard.js
>  } from 'flight-webapp-components';
I can only assume that it was some kind of blindness

2022-06-14 19:45 UTC, VoxSecundus commented on src/SessionCard.js
> +    flexWrap: 'nowrap'
Assuming the session card rename button is staying gone until we can find a solid wrapping solution, it is not needed.

2022-06-14 19:47 UTC, VoxSecundus commented on src/launch-and-access-desktop-session.test.js
> +  const launchButton = within(card).getByTestId('launch-modal-button');
I did read that. I wasn't able to easily find a way to reference each of the `Launch` buttons based on their parent elements, so I resorted to `getByTestId`. If you know of a better way I can get the `Launch` buttons off the cuff, please let me know and I'll change this/

2022-06-15 15:46 UTC, benarmston approved these changes
LGTM.

2022-06-15 15:46 UTC, merged