Link to Flight Job overview for sessions started by Job
openflighthpc/flight-desktop-webapp pull request #92
Opened 2022-06-17 15:06 UTC by VoxSecundus

This PR adds the ability to navigate to the Flight Job Webapp overview for Desktop sessions which were started by Flight Job. When the session was not launched via Flight Job, the behaviour is as usual.

## Session card

A new row has been added to the session card metadata (see below), showing the job ID as a hyperlink to the Flight Job Webapp page.

![Screenshot_2022-06-17_16-02-57](https://user-images.githubusercontent.com/12374447/174324853-93eddcf8-8440-43e3-b3d6-e6c618d3c445.png)

## Session page

The session ID on the session page has been turned into a similarly clickable link (see below), with an icon next to it to indicate that it is a link.

![Screenshot_2022-06-17_16-03-15](https://user-images.githubusercontent.com/12374447/174324964-a729c97c-c2c8-4985-9583-0b9de287655c.png)

2022-06-17 15:14 UTC, benarmston requested changes
Thanks for the screenshots.  For the second screenshot, the name would be the link if the session has a name; otherwise it would be the id.  That way the same text "desktop-on-log-4" would be linked in both places.  Obviously, that last point doesn't necessarily hold if the name is changed, but it does by default.

2022-06-17 15:33 UTC, VoxSecundus commented
Thanks for the feedback @benarmston; I've updated the page to match what you've described (and `git commit --amend`ed it instead of adding it to a new commit; sorry!)

2022-06-17 15:52 UTC, benarmston requested changes
A few comments for you to look at please.

2022-06-17 15:52 UTC, benarmston commented on src/SessionPage.js
> +    <span>{sessionName} ({idText}) {hostname}</span>;
Looks like its time to extract all of this into a new component.  Perhaps it was time to do so before to be honest.  Could you create a new, say, `HeaderText` component and replace `{title}` on line 210(ish) with a call to `HeaderText`.

2022-06-17 15:52 UTC, benarmston commented on src/SessionPage.js
> +function JobLink({session, children}) {
Good idea extracting this.

2022-06-17 15:52 UTC, benarmston commented on src/SessionPage.js
> +      rel="noreferrer noopener"
None of our other inter-app links open in a new tab.  We should be consistent and not do so with these links either.

2022-06-17 15:52 UTC, benarmston commented on src/SessionCard.js
> +      format={id => <a href={jobUrl} target="_blank" rel="noreferrer noopener">{id}</a> }
See other comment about opening in new tabs.

2022-06-17 16:37 UTC, benarmston requested changes
Can you have a go at cleaning up the new `HeaderText` component.  It should be simpler to do so now that its its own component.

2022-06-17 16:37 UTC, benarmston commented on src/HeaderText.js
> +  return (title)
Now that this is extracted to its own component we have a chance to refactor to improve the clarity of what cases it is handling and how.

The cases that its handling are:

1. The session is null (presumably its being loaded).
2. The session has a name and a job id.
3. The session has a name, but not a job id.
4. The session does not have a name, but does have a job id.
5. The session does not have a name and does not have a job id.

Early returns and possibly extracting additional components might help here.

2022-06-17 17:17 UTC, benarmston requested changes
Looks like you're on the right lines...

2022-06-20 15:55 UTC, benarmston approved these changes
I've added a commit which renames `HeaderText` to `SessionHeaderText` and adjusts the tooltips and icons.  Nothing major.

This looks good to me know.

2022-06-20 15:56 UTC, merged